# Generated by Django 4.2.6 on 2024-01-06 12:31

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=300, unique=True, verbose_name='Branch Name')),
                ('branch_category', models.CharField(choices=[('', ''), ('workshop', 'Workshop'), ('warehouse', 'Warehouse')], default='', max_length=300, verbose_name='Category')),
                ('branch_type', models.CharField(choices=[('', ''), ('main', 'Main'), ('sub', 'Sub')], default='', max_length=100, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=300, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('emp_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('emp_bdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('emp_nation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality')),
                ('emp_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('emp_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('emp_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('emp_hired', models.DateField(blank=True, null=True, verbose_name='Date Hired')),
                ('emp_position', models.CharField(blank=True, max_length=300, null=True, verbose_name='Position')),
                ('emp_salary', models.CharField(blank=True, max_length=300, null=True, verbose_name='Salary Grade')),
                ('emp_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.branch', verbose_name='Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Code')),
                ('item_name', models.CharField(max_length=100, verbose_name='Name')),
                ('item_category', models.CharField(max_length=200, verbose_name='Category')),
                ('item_location', models.CharField(max_length=200, verbose_name='Physical Location')),
                ('item_measurement', models.CharField(max_length=200, verbose_name='Unit Of Measurement')),
                ('item_reorder', models.FloatField(verbose_name='Reorder Quantity')),
                ('item_onhand', models.FloatField(blank=True, null=True, verbose_name='Quantity On Hand')),
                ('item_cost', models.FloatField(verbose_name='Unit Cost')),
                ('item_description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Section Label')),
                ('key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Key')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Name')),
                ('shift_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('shift_from', models.TimeField(blank=True, null=True, verbose_name='From')),
                ('shift_to', models.TimeField(blank=True, null=True, verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('trans_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Type')),
                ('trans_action', models.CharField(blank=True, max_length=300, null=True, verbose_name='Action')),
                ('trans_date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('trans_user', models.CharField(blank=True, max_length=300, null=True, verbose_name='User')),
                ('trans_detail', models.TextField(blank=True, null=True, verbose_name='Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Code')),
                ('vehicle_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type')),
                ('vehicle_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('vehicle_serial', models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial')),
                ('vehicle_plate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plate')),
                ('vehicle_area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Area')),
                ('vehicle_sector', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sector')),
                ('vehicle_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Warehouse Code')),
                ('warehouse_name', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Name')),
                ('warehouse_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.branch', verbose_name='Branch')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_location', models.CharField(max_length=200, verbose_name='Physical Location')),
                ('item_onhand', models.FloatField(blank=True, null=True, verbose_name='Quantity On Hand')),
                ('item_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.item', verbose_name='Item Code')),
                ('warehouse_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.warehouse', verbose_name='Warehouse Code')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Vacation Type')),
                ('vac_start', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('vac_end', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('vac_reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('vac_attachment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Attachment')),
                ('vac_total', models.CharField(blank=True, max_length=200, null=True, verbose_name='Total')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.employee', verbose_name='Employee ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sched_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('sched_fri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_fri', to='ams.shift', verbose_name='Friday')),
                ('sched_mon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_mon', to='ams.shift', verbose_name='Monday')),
                ('sched_sat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_sat', to='ams.shift', verbose_name='Satuday')),
                ('sched_sun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_sun', to='ams.shift', verbose_name='Sunday')),
                ('sched_thu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_thu', to='ams.shift', verbose_name='Thurdsay')),
                ('sched_tue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_tue', to='ams.shift', verbose_name='Tuesday')),
                ('sched_wed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_wed', to='ams.shift', verbose_name='Wednesday')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_name', models.CharField(max_length=200, verbose_name='Option Name')),
                ('opt_value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Value')),
                ('opt_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Module Label')),
                ('key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Key')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon')),
                ('children', models.ManyToManyField(blank=True, to='ams.section', verbose_name='Children')),
            ],
        ),
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exc_date', models.DateField(blank=True, null=True, verbose_name='Excuse Date')),
                ('exc_start', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('exc_end', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('exc_reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('exc_total', models.CharField(blank=True, max_length=200, null=True, verbose_name='Total')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.employee', verbose_name='Employee ID')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_sched',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.schedule', verbose_name='Schedule'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.DateField(verbose_name='Date')),
                ('attend_checkin', models.DateTimeField(blank=True, null=True, verbose_name='Check In')),
                ('attend_checkout', models.DateTimeField(blank=True, null=True, verbose_name='Check Out')),
                ('attend_latein', models.FloatField(blank=True, null=True, verbose_name='Late In')),
                ('attend_earlyout', models.FloatField(blank=True, null=True, verbose_name='Early Out')),
                ('attend_work', models.FloatField(blank=True, null=True, verbose_name='Worked')),
                ('attend_req', models.FloatField(blank=True, null=True, verbose_name='Required')),
                ('attend_under', models.FloatField(blank=True, null=True, verbose_name='Undertime')),
                ('attend_over', models.FloatField(blank=True, null=True, verbose_name='Overtime')),
                ('attend_excuse', models.FloatField(blank=True, null=True, verbose_name='Excuse')),
                ('attend_status', models.CharField(blank=True, max_length=300, null=True, verbose_name='Status')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.employee', verbose_name='Employee ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('empID', models.PositiveIntegerField(blank=True, null=True, verbose_name='Employee ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
