# Generated by Django 4.1.5 on 2023-02-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
