# Generated by Django 4.2.6 on 2024-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='option',
            name='opt_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Option Name'),
        ),
    ]
