# Generated by Django 4.2.6 on 2024-01-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_alter_category_cat_name_alter_option_opt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sched_name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Name'),
        ),
    ]
