# Generated by Django 4.2.6 on 2024-01-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_alter_schedule_sched_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_onhand',
        ),
    ]
