# Generated by Django 4.1.5 on 2023-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_nationality_position_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
