# Generated by Django 4.2.6 on 2024-01-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_remove_item_item_location_remove_item_item_onhand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
