# Generated by Django 4.2.6 on 2024-01-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_remove_transaction_trans_id_transaction_trans_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trans_type',
            new_name='trans_action',
        ),
    ]
