# Generated by Django 4.2.6 on 2024-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_rename_trans_type_transaction_trans_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_status',
            field=models.TextField(blank=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_action',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='item_location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
    ]
