# Generated by Django 4.1.5 on 2023-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_remove_employee_emp_dayoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=500, verbose_name='Item ID')),
                ('item_name', models.TextField(verbose_name='Name')),
                ('item_cost', models.PositiveIntegerField(verbose_name='Cost')),
                ('item_description', models.TextField(verbose_name='Description')),
                ('item_category', models.CharField(max_length=500, verbose_name='Category')),
                ('item_measurement', models.CharField(max_length=500, verbose_name='Measurement')),
                ('item_location', models.CharField(max_length=300, verbose_name='Location')),
                ('item_onhand', models.PositiveIntegerField(verbose_name='Quantity On Hand')),
                ('item_reorder', models.PositiveIntegerField(verbose_name='Reorder Quantity')),
            ],
        ),
    ]
