# Generated by Django 4.2.6 on 2024-03-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_transaction_trans_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='empID',
            new_name='userid',
        ),
    ]
