# Generated by Django 4.1.5 on 2023-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Item ID'),
        ),
    ]
