# Generated by Django 4.2.6 on 2024-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_alter_warehouseitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
