# Generated by Django 4.2.6 on 2024-01-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_alter_warehouseitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
