# Generated by Django 4.1.5 on 2023-06-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_alter_item_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='item_code',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Monthly Salary'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.FloatField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_onhand',
            field=models.FloatField(verbose_name='Quantity On Hand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_reorder',
            field=models.FloatField(verbose_name='Reorder Quantity'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.FloatField(verbose_name='Salary'),
        ),
    ]
