# Generated by Django 4.2.6 on 2024-01-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_alter_warehouseitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_name',
        ),
    ]
