# Generated by Django 4.2.6 on 2024-04-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_asset_delete_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Category'),
        ),
    ]
