# Generated by Django 4.1.5 on 2023-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_rename_item_id_item_item_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=300, verbose_name='Measurement')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.FloatField(verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_location',
            field=models.CharField(max_length=300, verbose_name='Physical Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_measurement',
            field=models.CharField(max_length=500, verbose_name='Unit Of Measurement'),
        ),
    ]
