# Generated by Django 4.1.5 on 2023-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0009_category_measurement_alter_item_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_onhand',
            field=models.CharField(max_length=10, verbose_name='Quantity On Hand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_reorder',
            field=models.CharField(max_length=10, verbose_name='Reorder Quantity'),
        ),
    ]
