# Generated by Django 4.1.5 on 2023-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0010_alter_item_item_onhand_alter_item_item_reorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.CharField(max_length=10, verbose_name='Unit Cost'),
        ),
    ]
