# Generated by Django 4.1.5 on 2023-06-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0011_alter_item_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.FloatField(verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_onhand',
            field=models.FloatField(verbose_name='Quantity On Hand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_reorder',
            field=models.FloatField(verbose_name='Reorder Quantity'),
        ),
    ]
