# Generated by Django 4.2.6 on 2024-04-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0012_alter_asset_asset_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workorder',
        ),
    ]
