# Generated by Django 4.1.5 on 2023-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0012_alter_item_item_cost_alter_item_item_onhand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_onhand',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantity On Hand'),
        ),
    ]
