# Generated by Django 3.2.20 on 2023-07-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_alter_item_item_onhand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation', models.CharField(max_length=500, verbose_name='Vacation')),
            ],
        ),
    ]
