# Generated by Django 4.2.6 on 2024-04-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0013_delete_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_code', models.CharField(blank=True, max_length=300, null=True, verbose_name='Workorder Code')),
                ('asset_kilo', models.IntegerField(blank=True, null=True, verbose_name='Kilometer')),
                ('work_date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('work_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Type')),
                ('work_status', models.CharField(blank=True, max_length=300, null=True, verbose_name='Status')),
                ('maint_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Maintenance Type')),
                ('recep_remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('asset_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.asset', verbose_name='Asset Code')),
                ('recep_sched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recep_sched', to='ams.employee', verbose_name='Scheduler')),
                ('recep_sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recep_sup', to='ams.employee', verbose_name='Supervisor')),
                ('recep_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recep_tech', to='ams.employee', verbose_name='Technician')),
                ('work_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.section', verbose_name='Workshop Code')),
            ],
        ),
    ]
