# Generated by Django 4.2.6 on 2024-04-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0014_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.branch', verbose_name='Area'),
        ),
    ]
