# Generated by Django 4.2.6 on 2024-04-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0015_alter_asset_asset_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='work_shop',
            new_name='workshop_code',
        ),
    ]
