# Generated by Django 3.2.20 on 2023-08-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0015_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.category', verbose_name='Category'),
        ),
    ]
