# Generated by Django 3.2.20 on 2023-08-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0016_alter_option_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ams.shift', verbose_name='Category'),
        ),
    ]
