# Generated by Django 4.2.6 on 2024-04-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0016_rename_work_shop_workorder_workshop_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_code', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Operation Code')),
                ('op_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('op_hours', models.FloatField(blank=True, null=True, verbose_name='Standard Hours')),
                ('op_item', models.BooleanField(default=False, verbose_name='Item Required')),
                ('op_restriction', models.TextField(blank=True, null=True, verbose_name='Restriction')),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Type')),
                ('op_rate', models.FloatField(blank=True, null=True, verbose_name='Rate')),
            ],
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='maint_type',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='recep_sup',
        ),
        migrations.AddField(
            model_name='workorder',
            name='recep_supv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recep_supv', to='ams.employee', verbose_name='Supervisor'),
        ),
        migrations.CreateModel(
            name='WorkorderOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.operation', verbose_name='Operation Code')),
                ('op_sched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_sched', to='ams.employee', verbose_name='Scheduler')),
                ('op_supv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_supv', to='ams.employee', verbose_name='Supervisor')),
                ('op_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.operationtype', verbose_name='Type')),
                ('work_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.workorder', verbose_name='Workorder Code')),
            ],
        ),
        migrations.CreateModel(
            name='OperationTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_rate', models.FloatField(blank=True, null=True, verbose_name='Rate')),
                ('op_hours', models.FloatField(blank=True, null=True, verbose_name='Standard Hours')),
                ('tech_hours', models.FloatField(blank=True, null=True, verbose_name='Technician Hours')),
                ('total_cost', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('op_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.operation', verbose_name='Operation Code')),
                ('op_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.employee', verbose_name='Technician')),
                ('work_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.workorder', verbose_name='Workorder Code')),
            ],
        ),
        migrations.CreateModel(
            name='OperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_cost', models.FloatField(blank=True, null=True, verbose_name='Unit Cost')),
                ('item_quantity', models.FloatField(blank=True, null=True, verbose_name='Item Quantity')),
                ('total_cost', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.item', verbose_name='Item Code')),
                ('op_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.operation', verbose_name='Operation Code')),
                ('work_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.workorder', verbose_name='Workorder Code')),
            ],
        ),
    ]
