# Generated by Django 3.2.20 on 2023-08-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0017_alter_option_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='cat_name',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='name',
            new_name='opt_name',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='value',
            new_name='opt_value',
        ),
        migrations.RemoveField(
            model_name='option',
            name='category',
        ),
        migrations.AddField(
            model_name='option',
            name='opt_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt_category', to='ams.category', verbose_name='Category'),
        ),
    ]
