# Generated by Django 4.2.6 on 2024-04-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0017_operation_operationtype_remove_workorder_maint_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='recep_remarks',
        ),
        migrations.AddField(
            model_name='workorder',
            name='recep_diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='op_type',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Operation Type'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Workorder Type'),
        ),
        migrations.AlterField(
            model_name='workorderoperation',
            name='op_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.operationtype', verbose_name='Operation Type'),
        ),
    ]
