# Generated by Django 3.2.20 on 2023-08-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0018_auto_20230826_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='opt_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opt_categor', to='ams.category', verbose_name='Category'),
        ),
    ]
