# Generated by Django 3.2.20 on 2023-08-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0021_alter_option_opt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salary Grade'),
        ),
    ]
