# Generated by Django 3.2.20 on 2023-08-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0022_alter_employee_emp_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
    ]
