# Generated by Django 3.2.20 on 2023-08-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0023_auto_20230826_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_nation',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_position',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Salary Grade'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(max_length=300, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_measurement',
            field=models.CharField(max_length=300, verbose_name='Unit Of Measurement'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_type', models.CharField(max_length=300, verbose_name='Vacation Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('vac_total', models.CharField(max_length=100, verbose_name='Total')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.employee', verbose_name='Employee ID')),
            ],
        ),
    ]
