# Generated by Django 3.2.20 on 2023-08-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0024_auto_20230826_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='opt_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vac_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.option', verbose_name='Vacation Type'),
        ),
    ]
