# Generated by Django 3.2.20 on 2023-08-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0026_auto_20230826_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vac_type',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Vacation Type'),
        ),
    ]
