# Generated by Django 3.2.20 on 2023-09-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0027_alter_vacation_vac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attend_checkin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend_checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check Out'),
        ),
    ]
