# Generated by Django 3.2.20 on 2023-10-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0028_auto_20230902_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exc_date', models.DateField(blank=True, null=True, verbose_name='Excuse Date')),
                ('exc_start', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('exc_end', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('exc_reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('exc_total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ams.employee', verbose_name='Employee ID')),
            ],
        ),
    ]
