# Generated by Django 4.2.6 on 2023-11-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0029_excuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('trans_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='Type')),
                ('trans_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('trans_user', models.CharField(blank=True, max_length=200, null=True, verbose_name='User')),
                ('trans_detail', models.TextField(blank=True, null=True, verbose_name='Detail')),
            ],
        ),
    ]
