# Generated by Django 4.2.6 on 2023-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0030_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
