# Generated by Django 4.2.6 on 2023-11-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0031_alter_transaction_trans_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_action',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Action'),
        ),
    ]
