# Generated by Django 4.2.6 on 2023-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0032_transaction_trans_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_from',
            field=models.TimeField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_to',
            field=models.TimeField(blank=True, null=True, verbose_name='To'),
        ),
    ]
