# Generated by Django 4.2.6 on 2023-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0033_alter_shift_shift_from_alter_shift_shift_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
