# Generated by Django 4.2.6 on 2023-11-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0034_shift_shift_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
    ]
