# Generated by Django 4.2.6 on 2023-11-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0035_alter_shift_shift_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sched_fri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_fri', to='ams.shift', verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sched_mon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_mon', to='ams.shift', verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sched_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sched_sat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_sat', to='ams.shift', verbose_name='Satuday'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sched_sun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_sun', to='ams.shift', verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sched_thu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_thu', to='ams.shift', verbose_name='Thurdsay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sched_tue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_tue', to='ams.shift', verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sched_wed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sched_wed', to='ams.shift', verbose_name='Wednesday'),
        ),
    ]
