# Generated by Django 4.2.6 on 2023-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0036_alter_schedule_sched_fri_alter_schedule_sched_mon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_nation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='exc_total',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='option',
            name='opt_name',
            field=models.CharField(max_length=200, verbose_name='Option Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_action',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_user',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vac_attachment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vac_total',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Total'),
        ),
    ]
