# Generated by Django 4.2.6 on 2023-12-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0037_alter_employee_emp_nation_alter_excuse_exc_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Name'),
        ),
    ]
