# Generated by Django 4.2.6 on 2023-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0038_alter_employee_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
