# Generated by Django 4.2.6 on 2023-12-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0039_alter_employee_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Code')),
                ('asset_type', models.CharField(max_length=200, verbose_name='Type')),
                ('asset_model', models.CharField(max_length=200, verbose_name='Model')),
                ('asset_serial', models.CharField(max_length=300, verbose_name='Serial')),
                ('asset_plate', models.CharField(max_length=100, verbose_name='Plate')),
                ('asset_area', models.CharField(max_length=200, verbose_name='Area')),
                ('asset_sector', models.CharField(max_length=300, verbose_name='Sector')),
                ('asset_status', models.CharField(max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(max_length=200, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_location',
            field=models.CharField(max_length=200, verbose_name='Physical Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_measurement',
            field=models.CharField(max_length=200, verbose_name='Unit Of Measurement'),
        ),
    ]
