# Generated by Django 4.2.6 on 2023-12-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0040_asset_alter_item_item_category_alter_item_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_plate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plate'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_sector',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_serial',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type'),
        ),
    ]
