# Generated by Django 4.2.6 on 2024-01-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0044_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_location', models.CharField(max_length=200, verbose_name='Physical Location')),
                ('item_onhand', models.FloatField(blank=True, null=True, verbose_name='Quantity On Hand')),
                ('item_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.item', verbose_name='Item Code')),
                ('warehouse_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.warehouse', verbose_name='Warehouse Code')),
            ],
        ),
    ]
