# Generated by Django 4.2.6 on 2024-01-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0045_warehouseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_branch',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Branch'),
        ),
    ]
